import { Client, Message } from './types';

export const seedClients: Client[] = [
  {
    id: 'martinez',
    firmName: 'Farah & Farah Personal Injury Lawyers',
    contactName: 'Eddie Farah',
    email: 'eddie@farahlaw.com',
    phone: '(305) 555-0142',
    status: 'Active',
    personality: 'aggressive',
    order: {
      practiceArea: 'Personal Injury',
      leadsPerMonth: 200,
      costPerLead: 45,
      monthlyBudget: 9000,
      startDate: '2025-08-15',
      notes: 'Wants exclusive leads in Miami-Dade. Very price sensitive.',
    },
    createdAt: '2025-08-10T14:00:00Z',
  },
  {
    id: 'chen',
    firmName: 'Hector Hernández & Associate, P.A',
    contactName: 'Hector Hernandez',
    email: 'hector@hernandezlaw.com',
    phone: '(415) 555-0198',
    status: 'Active',
    personality: 'passive',
    order: {
      practiceArea: 'Workers Compensation',
      leadsPerMonth: 100,
      costPerLead: 55,
      monthlyBudget: 5500,
      startDate: '2025-09-01',
      notes: 'Bay Area focus. Happy with current volume.',
    },
    createdAt: '2025-08-25T10:00:00Z',
  },
  {
    id: 'obrien',
    firmName: "O'Brien Law Offices",
    contactName: "Patrick O'Brien",
    email: 'pobrien@obrienlaw.com',
    phone: '(312) 555-0167',
    status: 'Negotiating',
    personality: 'skeptical',
    order: {
      practiceArea: 'Medical Malpractice',
      leadsPerMonth: 50,
      costPerLead: 120,
      monthlyBudget: 6000,
      startDate: null,
      notes: 'Wants proof of lead quality before committing. Requested case studies.',
    },
    createdAt: '2025-10-05T09:00:00Z',
  },
  {
    id: 'davis',
    firmName: 'Davis & Partners',
    contactName: 'James Davis',
    email: 'jdavis@davispartners.com',
    phone: '(404) 555-0133',
    status: 'Active',
    personality: 'growth',
    order: {
      practiceArea: 'Criminal Defense',
      leadsPerMonth: 150,
      costPerLead: 35,
      monthlyBudget: 5250,
      startDate: '2025-07-01',
      notes: 'Expanding to 3 new markets. Wants to double volume by Q2.',
    },
    createdAt: '2025-06-20T11:00:00Z',
  },
  {
    id: 'nakamura',
    firmName: 'Nakamura Legal',
    contactName: 'Yuki Nakamura',
    email: 'yuki@nakamuralaw.com',
    phone: '(206) 555-0155',
    status: 'Paused',
    personality: 'passive',
    order: {
      practiceArea: 'Immigration',
      leadsPerMonth: 75,
      costPerLead: 40,
      monthlyBudget: 3000,
      startDate: '2025-05-15',
      notes: 'Paused due to staffing changes. Will resume in spring.',
    },
    createdAt: '2025-05-01T13:00:00Z',
  },
  {
    id: 'blackwell',
    firmName: 'Blackwell & Associates',
    contactName: 'Diana Blackwell',
    email: 'diana@blackwelllaw.com',
    phone: '(713) 555-0189',
    status: 'Negotiating',
    personality: 'aggressive',
    order: {
      practiceArea: 'Mass Tort',
      leadsPerMonth: 300,
      costPerLead: 65,
      monthlyBudget: 19500,
      startDate: null,
      notes: 'Biggest potential account. Wants volume discount below $55/lead.',
    },
    createdAt: '2025-11-01T08:00:00Z',
  },
  {
    id: 'sullivan',
    firmName: 'Sullivan Law Firm',
    contactName: 'Mary Sullivan',
    email: 'mary@sullivanlawfirm.com',
    phone: '(617) 555-0121',
    status: 'New Lead',
    personality: 'skeptical',
    order: {
      practiceArea: 'Family Law',
      leadsPerMonth: null,
      costPerLead: null,
      monthlyBudget: null,
      startDate: null,
      notes: 'Inbound from website. Interested but has not discussed pricing.',
    },
    createdAt: '2026-01-10T15:00:00Z',
  },
  {
    id: 'reeves',
    firmName: 'Reeves & Goldstein',
    contactName: 'David Goldstein',
    email: 'dgold@reevesgoldstein.com',
    phone: '(212) 555-0177',
    status: 'Active',
    personality: 'growth',
    order: {
      practiceArea: 'Personal Injury',
      leadsPerMonth: 250,
      costPerLead: 50,
      monthlyBudget: 12500,
      startDate: '2025-06-01',
      notes: 'Top performer. Looking to expand into NJ and CT markets.',
    },
    createdAt: '2025-05-20T10:00:00Z',
  },
  {
    id: 'thompson',
    firmName: 'Thompson Legal',
    contactName: 'Sarah Thompson',
    email: 'sthompson@thompsonlegal.com',
    phone: '(602) 555-0144',
    status: 'New Lead',
    personality: 'passive',
    order: {
      practiceArea: 'Social Security Disability',
      leadsPerMonth: null,
      costPerLead: null,
      monthlyBudget: null,
      startDate: null,
      notes: 'Referred by Reeves & Goldstein. Initial call scheduled.',
    },
    createdAt: '2026-02-01T09:00:00Z',
  },
  {
    id: 'kowalski',
    firmName: 'Kowalski & Sharp',
    contactName: 'Mike Kowalski',
    email: 'mkowalski@kowalskisharp.com',
    phone: '(216) 555-0166',
    status: 'Active',
    personality: 'aggressive',
    order: {
      practiceArea: 'Workers Compensation',
      leadsPerMonth: 175,
      costPerLead: 48,
      monthlyBudget: 8400,
      startDate: '2025-09-15',
      notes: 'Ohio exclusive. Constantly pushes for lower CPL.',
    },
    createdAt: '2025-09-10T12:00:00Z',
  },
];

export const seedMessages: Message[] = [
  // Farah & Farah
  {
    id: 'msg-m1',
    clientId: 'martinez',
    content: 'Eddie, happy to report we delivered 215 leads last month. Quality scores are trending up too.',
    role: 'user',
    timestamp: '2026-03-15T10:00:00Z',
  },
  {
    id: 'msg-m2',
    clientId: 'martinez',
    content: "215 is fine but I need the CPL down to $40. We're getting quotes from LeadGenPro at $38.",
    role: 'client',
    timestamp: '2026-03-15T10:05:00Z',
  },
  {
    id: 'msg-m3',
    clientId: 'martinez',
    content: "I understand you're comparing options. Our conversion rate is 18% vs industry average of 9%. That ROI gap more than covers the $7 difference.",
    role: 'user',
    timestamp: '2026-03-15T10:08:00Z',
  },
  // Hernandez
  {
    id: 'msg-c1',
    clientId: 'chen',
    content: 'Hi Hector, just checking in on this month\'s campaign. Everything running smoothly on your end?',
    role: 'user',
    timestamp: '2026-03-20T14:00:00Z',
  },
  {
    id: 'msg-c2',
    clientId: 'chen',
    content: 'Yes, everything looks great! The leads have been really solid. Thank you for checking in.',
    role: 'client',
    timestamp: '2026-03-20T14:15:00Z',
  },
  // O'Brien
  {
    id: 'msg-o1',
    clientId: 'obrien',
    content: "Patrick, I've put together the case study you requested showing lead-to-case conversion rates for our med mal clients.",
    role: 'user',
    timestamp: '2026-03-18T11:00:00Z',
  },
  {
    id: 'msg-o2',
    clientId: 'obrien',
    content: "I'll look at it. But $120 per lead is steep. What's the average case value your leads generate?",
    role: 'client',
    timestamp: '2026-03-18T11:30:00Z',
  },
  // Davis
  {
    id: 'msg-d1',
    clientId: 'davis',
    content: 'James, the Atlanta expansion is live. We can start routing leads to your new office next week.',
    role: 'user',
    timestamp: '2026-03-22T09:00:00Z',
  },
  {
    id: 'msg-d2',
    clientId: 'davis',
    content: "That's amazing! Can we also look at Birmingham and Nashville? I want to be in 5 markets by summer.",
    role: 'client',
    timestamp: '2026-03-22T09:10:00Z',
  },
  // Blackwell
  {
    id: 'msg-b1',
    clientId: 'blackwell',
    content: "Diana, I've prepared a custom volume pricing proposal for 300 leads/month. Shall we walk through it?",
    role: 'user',
    timestamp: '2026-03-25T16:00:00Z',
  },
  {
    id: 'msg-b2',
    clientId: 'blackwell',
    content: "Send it over. But if it's not under $55 a lead don't waste my time. We have 3 other vendors ready to go.",
    role: 'client',
    timestamp: '2026-03-25T16:05:00Z',
  },
  // Reeves
  {
    id: 'msg-r1',
    clientId: 'reeves',
    content: 'David, great month — 267 leads delivered with a 22% contact rate. Ready to discuss the NJ expansion?',
    role: 'user',
    timestamp: '2026-03-28T13:00:00Z',
  },
  {
    id: 'msg-r2',
    clientId: 'reeves',
    content: 'Absolutely. Those numbers are fantastic. What would it take to add 100 leads/month in Newark and Jersey City?',
    role: 'client',
    timestamp: '2026-03-28T13:12:00Z',
  },
  // Kowalski
  {
    id: 'msg-k1',
    clientId: 'kowalski',
    content: "Mike, your March delivery is at 180 leads. We're 5 over target this month.",
    role: 'user',
    timestamp: '2026-03-30T10:00:00Z',
  },
  {
    id: 'msg-k2',
    clientId: 'kowalski',
    content: "Good. But I want a better rate. $48 is too high for workers comp in Ohio. I know what others are charging.",
    role: 'client',
    timestamp: '2026-03-30T10:08:00Z',
  },
];
